project_id = "sneahvpzwjbmjsqbducw"

[functions.check-eligibility]
verify_jwt = true

[functions.evaluate-customer-evidence]
verify_jwt = true

[functions.proceed-to-prearbitration]
verify_jwt = true

[functions.close-after-customer-evidence]
verify_jwt = true

[functions.analyze-custom-reason]
verify_jwt = true

[functions.verify-documents]
verify_jwt = true

[functions.clear-all-data]
verify_jwt = false

[functions.process-chargeback-action]
verify_jwt = true

[functions.delete-conversation]
verify_jwt = true

[functions.evaluate-decision]
verify_jwt = true

[functions.accept-representment]
verify_jwt = true

[functions.reject-representment]
verify_jwt = true

[functions.answer-help-question]
verify_jwt = true

[functions.chargeback-precheck]
verify_jwt = true

[functions.approve-customer-evidence]
verify_jwt = true

[functions.reject-customer-evidence]
verify_jwt = true

[functions.query-knowledge-base]
verify_jwt = true

[functions.update-knowledge-base]
verify_jwt = true

[functions.log-transaction-update]
verify_jwt = true

[functions.extract-invoice-data]
verify_jwt = true